yyast-0.2: yyast/error.c File Reference
yyast/error.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <yyast/error.h>
#include <yyast/count.h>
Functions
void ya_error (const char *message,...)
Function Documentation
void ya_error (const char * message, ...)
Definition at line 22 of file error.c.
References ya_position_s::column, ya_position_s::line, and ya_current_position.
Referenced by ya_binary_float(), ya_integer(), and ya_string_escape().