yyast-0.2: yyast/main.h File Reference
yyast/main.h File Reference
Functions
int ya_main (int argc, char *argv[], char *extension)
Function Documentation
int ya_main (int argc, char * argv[], char * extension)
Definition at line 94 of file main.c.
References ya_input_filename, ya_node_save(), ya_output_filename, ya_parse_options(), ya_reposition(), ya_start, yyin, and yyparse().