yyast-0.2: yyast/main.c File Reference
yyast/main.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <getopt.h>
#include <yyast/main.h>
#include <yyast/utils.h>
#include <yyast/node.h>
#include <yyast/count.h>
Functions
int yyparse ()
void ya_usage (int exit_code)
void ya_parse_options (int argc, char *argv[], char *extension)
int ya_main (int argc, char *argv[], char *extension)
Variables
FILE * yyin
char * ya_output_filename = NULL
char * ya_input_filename = NULL
Function Documentation
int ya_main (int argc, char * argv[], char * extension)
Definition at line 94 of file main.c.
References ya_input_filename, ya_node_save(), ya_output_filename, ya_parse_options(), ya_reposition(), ya_start, yyin, and yyparse().
void ya_parse_options (int argc, char * argv[], char * extension)
Definition at line 43 of file main.c.
References ya_input_filename, ya_new_extension(), ya_output_filename, and ya_usage().
Referenced by ya_main().
void ya_usage (int exit_code)
Definition at line 29 of file main.c.
Referenced by ya_parse_options().
int yyparse ()
Referenced by ya_main().
Variable Documentation
char* ya_input_filename = NULL
Definition at line 27 of file main.c.
Referenced by ya_main(), and ya_parse_options().
char* ya_output_filename = NULL
Definition at line 26 of file main.c.
Referenced by ya_main(), and ya_parse_options().
FILE* yyin
Referenced by ya_main().
Generated for yyast-0.2 by 1.5.6