yyast-1.0.1: yyast/node.c File Reference
yyast/node.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <inttypes.h>
#include <stdint.h>
#include <math.h>
#include <limits.h>
#include <errno.h>
#include <unistd.h>
#include <string.h>
#include <stdarg.h>
#include <arpa/inet.h>
#include <yyast/node.h>
#include <yyast/utils.h>
#include <yyast/config.h>
#include <yyast/count.h>
Defines
#define _GNU_SOURCE
Functions
ya_t ya_generic_nodev (const char *restrict name, ya_type_t type, va_list ap)
ya_t ya_generic_node (const char *restrict name, ya_type_t type,...)
ya_t ya_branch (const char *restrict name,...)
Create an ya node.
ya_t ya_list (const char *restrict name,...)
Create an ya node.
void ya_node_save (FILE *output_file, ya_t *node)
Save the node to a file.
Variables
ya_t YA_NODE_DEFAULT
Define Documentation
#define _GNU_SOURCE
Definition at line 25 of file node.c.
Function Documentation
ya_t ya_branch (const char *restrict name, ...)
Create an ya node.
Create a node from subnodes. This will free memory used by the subnodes. If a list is added to a branch, then the nodes of the list are added to the created node, instead of the list itself.
Parameters:
name Name of the node.
... The subnodes, ending with NULL
Returns:
A new AST NODE.
Definition at line 151 of file node.c.
References ya_generic_nodev(), and YA_NODE_TYPE_BRANCH.
ya_t ya_generic_node (const char *restrict name, ya_type_t type, ...)
Definition at line 139 of file node.c.
References ya_generic_nodev().
ya_t ya_generic_nodev (const char *restrict name, ya_type_t type, va_list ap)
Definition at line 49 of file node.c.
References ya_position_s::column, ya_node_s::data, ya_position_s::file, ya_position_s::line, ya_t::node, ya_t::position, ya_t::size, ya_t::type, YA_NODE_TYPE_COUNT, YA_NODE_TYPE_LIST, and ya_previous_position.
Referenced by ya_branch(), ya_generic_node(), and ya_list().
ya_t ya_list (const char *restrict name, ...)
Create an ya node.
Create a list of subnodes, when included in a list or node, it expands as if the contents was passed as seperate items. This also free memory used by the subnodes.
Parameters:
name Name of the node. This should be '@list' because this function is called from the YA_LIST macro.
... The subnodes, ending with NULL
Returns:
A new AST NODE.
Definition at line 163 of file node.c.
References ya_generic_nodev(), and YA_NODE_TYPE_LIST.
void ya_node_save (FILE * output_file, ya_t * node)
Save the node to a file.
Parameters:
output_file A file pointer of an file open for writing.
node The node to be saved to file.
Definition at line 175 of file node.c.
References ya_t::node, and ya_t::size.
Referenced by ya_main().
Variable Documentation
ya_t YA_NODE_DEFAULT
Initial value:
 {
    .type  = YA_NODE_TYPE_NULL,
    .position = {.line = UINT32_MAX, .column = UINT32_MAX, .file = UINT32_MAX},
    .size  = sizeof (ya_node_t),
    .node  = NULL
}
Definition at line 42 of file node.c.
Generated for yyast-1.0.1 by 1.5.6