yyast-0.2: yyast/utils.h File Reference
yyast/utils.h File Reference
#include <stdlib.h>
#include <stdint.h>
#include <yyast/types.h>
#include <yyast/config.h>
Data Structures
union bswap128_t
Functions
uint128_t bswap128 (uint128_t x)
uint128_t htonlll (uint128_t x)
Host to network long long long (128).
unsigned long long htonll (unsigned long long x)
Host to network long long.
unsigned long long ntohll (unsigned long long x)
Network to host long long.
size_t ya_align64 (size_t x)
Align to a 64 bit boundary.
size_t ya_string_escape (uint8_t *string, size_t string_size, int raw)
Escape characters in a string.
char * ya_new_extension (char *filename, char *new_extension)
Strip extension from filename and replace with new extension.
Function Documentation
uint128_t bswap128 (uint128_t x) [inline]
Definition at line 30 of file utils.h.
References bswap128_t::in, and bswap128_t::v.
Referenced by htonlll().
unsigned long long htonll (unsigned long long x) [inline]
Host to network long long.
Definition at line 57 of file utils.h.
Referenced by ya_binary_float(), ya_generic_nodev(), ya_integer(), and ya_literal().
uint128_t htonlll (uint128_t x) [inline]
Host to network long long long (128).
Definition at line 46 of file utils.h.
References bswap128().
Referenced by ya_integer().
unsigned long long ntohll (unsigned long long x) [inline]
Network to host long long.
Definition at line 70 of file utils.h.
Referenced by node_decode().
size_t ya_align64 (size_t x) [inline]
Align to a 64 bit boundary.
Parameters:
x A size of an object in memory
Returns:
Either the size if it was aligned, or the next larger size that is aligned.
Definition at line 83 of file utils.h.
Referenced by node_decode(), and ya_literal().
char* ya_new_extension (char * filename, char * new_extension)
Strip extension from filename and replace with new extension.
Parameters:
filename The original filename.
new_extension The new extension to append.
Returns:
Filename with new extension, allocated.
Definition at line 132 of file utils.c.
Referenced by ya_parse_options().
size_t ya_string_escape (uint8_t * string, size_t string_size, int raw)
Escape characters in a string.
The original string is modified by this function.
Parameters:
string The UTF-8 string with escape characters.
string_size The number of bytes in the UTF-8 string.
raw When 0 standard escape sequence is decoded. When 1 only the double quote escape \" is decoded. When 2 only the double quote slash \/ is decoded.
Returns:
The number of characters after decoding.
Definition at line 27 of file utils.c.
References ya_error().