yyast-0.2: yyast/yadump.c File Reference
yyast/yadump.c File Reference
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <yyast/yyast.h>
Data Structures
union type64_t
Functions
void indent (unsigned int level)
void print_name (ya_name_t name)
off_t node_decode (char *buf, size_t buf_size, unsigned int level)
int main (int argc, char *argv[])
Function Documentation
void indent (unsigned int level)
Definition at line 30 of file yadump.c.
Referenced by node_decode().
int main (int argc, char * argv[])
Definition at line 143 of file yadump.c.
References node_decode().
off_t node_decode (char * buf, size_t buf_size, unsigned int level)
Definition at line 53 of file yadump.c.
References type64_t::c, ya_position_s::column, type64_t::d, ya_node_s::data, ya_position_s::file, type64_t::i, indent(), ya_position_s::line, ya_node_s::name, ntohll(), ya_node_s::position, print_name(), ya_node_s::size, ya_node_s::type, type64_t::u, ya_align64(), YA_NODE_TYPE_BINARY_FLOAT, YA_NODE_TYPE_BRANCH, YA_NODE_TYPE_NEGATIVE_INTEGER, YA_NODE_TYPE_NULL, YA_NODE_TYPE_POSITIVE_INTEGER, and YA_NODE_TYPE_TEXT.
Referenced by main().
void print_name (ya_name_t name)
Definition at line 39 of file yadump.c.
Referenced by node_decode().