

NODE_TYPE_NULL              = 0
NODE_TYPE_LEAF              = 1
NODE_TYPE_BRANCH            = 2
NODE_TYPE_TEXT              = 3
NODE_TYPE_POSITIVE_INTEGER  = 4
NODE_TYPE_NEGATIVE_INTEGER  = 5
NODE_TYPE_BINARY_FLOAT      = 6
NODE_TYPE_DECIMAL_FLOAT     = 7
